version: "3.8"
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}zigbee2mqtt
    mac_address: ${DOCKER_CONTAINER_MAC}
    networks:
      domotica_macvlan0:
        ipv4_address: ${DOCKER_IPV4}
    environment:
      - PUID=1
      - PGID=1
      - TZ=${DOCKER_TZ}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/zigbee2mqtt/data:/app/data
      - ${DOCKER_PATH_PERSISTENT}/zigbee2mqtt/run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    restart: unless-stopped
    devices:
      # Make sure this matched your adapter location
      port: /dev/ttyUSB0
    group_add:
      - dialout
    user: 1:1

networks:
  domotica_macvlan0:
    external: true
